# Pooling

Pooling 역시 마찬가지로, Window를 뽑고, 뽑아진 Window에서 스칼라 값을 구함

In [ ]:
이미지

pytorch에서 1d pooling은 (batch_size, channel, Length) 순으로 주어져야함

## 실습

### 1d Max Pooling

In [11]:
import numpy as np
import torch

L, kernel_size, s = 10, 2, 1

x = torch.randn(1, 1, L)

pool_max = torch.nn.MaxPool1d(kernel_size, stride = s)
pooled_max = pool_max(x)

print(f'x: {x.detach().numpy().shape} \n {x.detach().numpy().flatten()}')
print(f"pooled_max(Pytorch): {pooled_max.detach().numpy().shape} \n {pooled_max.detach().numpy().flatten()}")

x = x.detach().numpy().flatten()
pooled_max_man = np.zeros((L - kernel_size + 1, ))
for i in range(L-kernel_size+1):
    window = x[i:i+kernel_size]
    pooled_max_man[i] = np.max(window)
    
print(f"pooled max(Manual): {pooled_max_man.shape} \n {pooled_max_man}")

x: (1, 1, 10) 
 [-0.48127815  0.23707525  0.7108094   1.077727   -0.29472053  0.6619225
  1.108688   -1.179858    0.2866399   0.34239697]
pooled_max(Pytorch): (1, 1, 9) 
 [0.23707525 0.7108094  1.077727   1.077727   0.6619225  1.108688
 1.108688   0.2866399  0.34239697]
pooled max(Manual): (9,) 
 [0.23707525 0.71080941 1.07772696 1.07772696 0.66192251 1.108688
 1.108688   0.2866399  0.34239697]


### 1d Average Pooling

In [19]:
import numpy as np
import torch

L, kernel_size, s = 10, 2, 1

x = torch.randn(1, 1, L)

pool_avg = torch.nn.AvgPool1d(kernel_size, stride = s)
pooled_avg = pool_avg(x)

print(f'x: {x.detach().numpy().shape} \n {x.detach().numpy().flatten()}')
print(f"pooled_avg(Pytorch): {pooled_avg.detach().numpy().shape} \n {pooled_avg.detach().numpy().flatten()}")

x = x.detach().numpy().flatten()
pooled_avg_man = np.zeros((L - kernel_size + 1, ))
for i in range(L-kernel_size+1):
    window = x[i:i+kernel_size]
    pooled_avg_man[i] = np.mean(window)
    
print(f"pooled avg(Manual): {pooled_avg_man.shape} \n {pooled_avg_man}")

x: (1, 1, 10) 
 [-1.2186155  -1.367341   -1.0704515   0.9276175  -1.0581208   0.26181394
  0.9691664   1.3611132   0.67118055 -0.15293758]
pooled_avg(Pytorch): (1, 1, 9) 
 [-1.2929783  -1.2188963  -0.071417   -0.06525168 -0.39815345  0.6154902
  1.1651398   1.0161469   0.25912148]
pooled avg(Manual): (9,) 
 [-1.29297829 -1.21889627 -0.071417   -0.06525168 -0.39815345  0.6154902
  1.16513979  1.0161469   0.25912148]


### 2D Max Pooling

In [16]:
import numpy as np
import torch

N, I_h, I_w, I_c = 1, 5, 5, 1
kernel_size, s = 2, 1

x = torch.randn(N, I_c, I_h, I_w)

pool_max = torch.nn.MaxPool2d(kernel_size, stride = s)
pooled_max = pool_max(x)

print(f'x: {x.detach().numpy().shape} \n {x.detach().numpy().squeeze()}')
print(f"pooled_max(Pytorch): {pooled_max.detach().numpy().shape} \n {pooled_max.detach().numpy().squeeze()}")

x = x.detach().numpy().squeeze()
pooled_max_man = np.zeros((I_h - kernel_size + 1, I_w - kernel_size + 1))
for h in range(I_h - kernel_size + 1):
    for w in range(I_w - kernel_size + 1):
        window = x[h:h+kernel_size, w:w+kernel_size]
        pooled_max_man[h, w] = np.max(window)
    
print(f"pooled max(Manual): {pooled_max_man.shape} \n {pooled_max_man}")

x: (1, 1, 5, 5) 
 [[ 0.5980672  -2.2438042   1.3635836   0.5368877   0.00449439]
 [ 1.6102289   0.7236582  -1.3097978   0.7955343  -1.2279276 ]
 [-0.29437715 -0.36931333  0.8632904   0.11575136  0.38120705]
 [-0.72503644  0.6508263   0.9639564   0.66521883  0.2886386 ]
 [-0.29961133 -0.75649434 -0.45514402 -0.8236796   0.08192622]]
pooled_max(Pytorch): (1, 1, 4, 4) 
 [[1.6102289  1.3635836  1.3635836  0.7955343 ]
 [1.6102289  0.8632904  0.8632904  0.7955343 ]
 [0.6508263  0.9639564  0.9639564  0.66521883]
 [0.6508263  0.9639564  0.9639564  0.66521883]]
pooled max(Manual): (4, 4) 
 [[1.6102289  1.36358356 1.36358356 0.79553431]
 [1.6102289  0.86329043 0.86329043 0.79553431]
 [0.65082628 0.96395642 0.96395642 0.66521883]
 [0.65082628 0.96395642 0.96395642 0.66521883]]


### 2D Average Pooling

In [18]:
import numpy as np
import torch

N, I_h, I_w, I_c = 1, 5, 5, 1
kernel_size, s = 2, 1

x = torch.randn(N, I_c, I_h, I_w)

pool_avg = torch.nn.AvgPool2d(kernel_size, stride = s)
pooled_avg = pool_avg(x)

print(f'x: {x.detach().numpy().shape} \n {x.detach().numpy().squeeze()}')
print(f"pooled_avg(Pytorch): {pooled_avg.detach().numpy().shape} \n {pooled_avg.detach().numpy().squeeze()}")

x = x.detach().numpy().squeeze()
pooled_avg_man = np.zeros((I_h - kernel_size + 1, I_w - kernel_size + 1))
for h in range(I_h - kernel_size + 1):
    for w in range(I_w - kernel_size + 1):
        window = x[h:h+kernel_size, w:w+kernel_size]
        pooled_avg_man[h, w] = np.mean(window)
    
print(f"pooled avg(Manual): {pooled_avg_man.shape} \n {pooled_avg_man}")

x: (1, 1, 5, 5) 
 [[ 0.06052836 -2.2167168  -1.285001    0.6655307  -0.21489571]
 [ 0.03523486  0.05609528  1.4438839  -0.45838615 -1.2370079 ]
 [ 0.16763256  0.01920043 -1.1269134   0.4301835  -0.26899806]
 [ 0.74840206 -0.2769932   0.8327704  -0.17835443  0.96536404]
 [ 0.93571705 -3.1159606   1.6648691   0.2195827   0.7074069 ]]
pooled_avg(Pytorch): (1, 1, 4, 4) 
 [[-0.51621455 -0.50043464  0.09150685 -0.31118977]
 [ 0.06954078  0.09806654  0.07219195 -0.38355213]
 [ 0.16456047 -0.13798393 -0.01057848  0.23704876]
 [-0.42720866 -0.22382861  0.6347169   0.4284998 ]]
pooled avg(Manual): (4, 4) 
 [[-0.51621455 -0.50043464  0.09150685 -0.31118977]
 [ 0.06954078  0.09806654  0.07219195 -0.38355213]
 [ 0.16456047 -0.13798393 -0.01057848  0.23704876]
 [-0.42720866 -0.22382861  0.63471693  0.42849979]]


### 3D Max Pooling

In [28]:
import numpy as np
import torch
import math

N, I_h, I_w, I_c = 1, 5, 5, 3
kernel_size, s = 3, 2

x = torch.randn(N, I_c, I_h, I_w)

pool_max = torch.nn.MaxPool2d(kernel_size, stride = s)
pooled_max = pool_max(x)

print(f'x: {x.detach().numpy().shape} \n {x.detach().numpy().squeeze()}')
print(f"pooled_max(Pytorch): {pooled_max.detach().numpy().shape} \n {pooled_max.detach().numpy().squeeze()}")

x = x.detach().numpy().squeeze()
n_h = math.floor((I_h - kernel_size) / s + 1)
n_w = math.floor((I_w - kernel_size) / s + 1)
pooled_max_man = np.zeros((I_c, n_h, n_w))
for c in range(I_c):
    c_image = x[c, :, :]
    h_ = 0
    for h in range(0, I_h - kernel_size + 1, s):
        w_ = 0
        for w in range(0, I_w - kernel_size + 1, s):
            window = c_image[h:h+kernel_size, w:w+kernel_size]
            pooled_max_man[c, h_, w_] = np.max(window)
            
            w_ += 1
        h_ += 1

print(f"pooled max(Manual): {pooled_max_man.shape} \n {pooled_max_man}")

x: (1, 3, 5, 5) 
 [[[ 0.05906563  0.05523577  0.63052136  1.1241827  -1.1288646 ]
  [ 0.01653153  0.95838916  0.44448143  1.0860475   0.2632474 ]
  [ 0.48588365  0.01692184  0.23534581 -0.41104707  0.5483297 ]
  [-0.5807665  -0.90564317 -0.04516499 -0.5306638  -0.25007153]
  [ 0.31946895  0.31562537  1.4033486  -1.1616853   0.05355911]]

 [[-0.6798515   0.6181247  -0.04671555 -0.11321382 -0.66493547]
  [-1.5965999  -0.04826892 -0.0415714  -1.0064133   0.175527  ]
  [ 0.09091028 -1.149054    0.69600916  0.66423666 -2.7004225 ]
  [ 2.4790628   1.451201    0.05206729 -0.17382304 -0.17845514]
  [-1.1906714  -0.43878132 -0.46248004 -0.4247678  -0.80822676]]

 [[-1.2730048  -0.77286327 -2.1688619   1.900262   -0.15342268]
  [-1.4828472   1.2168839   0.32937896 -0.28536674 -0.78127897]
  [ 0.81398624  0.10998486  0.94279736 -1.1291951  -1.1023985 ]
  [ 0.7787801   0.7869182  -0.94710004  0.81030905  0.9698202 ]
  [ 1.2225664  -0.5677787  -0.26974285 -1.0920498   0.65839666]]]
pooled_max(Pytor

### Zero padding 2D

In [29]:
import numpy as np
import torch

images = torch.randn(1, 3, 28, 28)
print(images.detach().numpy().shape)

zero_padding = torch.nn.ZeroPad2d(padding = 2)
y = zero_padding(images)
print(y.detach().numpy().shape)

(1, 3, 28, 28)
(1, 3, 32, 32)


### Strides in Conv2D Layers

In [36]:
import torch

images = torch.randn(1, 3, 28, 28)

conv = torch.nn.Conv2d(3, 1, kernel_size = 3, padding = 1, stride = 2)
y = conv(images)

print(images.detach().numpy().shape)
print(y.detach().numpy().shape)

(1, 3, 28, 28)
(1, 1, 14, 14)


### Strides in Pooling Layers

In [35]:
import torch

images = torch.randn(1, 3, 28, 28)

pool = torch.nn.MaxPool2d(kernel_size = 3, stride = 2)
y = pool(images)

print(images.detach().numpy().shape)
print(y.detach().numpy().shape)

(1, 3, 28, 28)
(1, 3, 13, 13)
